defaults: &defaults
  environment:
    OPAMVERBOSE: 1
    OPAMYES: true
    TERM: xterm
  steps:
  - checkout
  - run:
      name: Configure environment
      command: echo . ~/.profile >> $BASH_ENV
  - run:
      name: List installed packages
      command: opam list
  - run:
      name: Build and install Metalib
      command: opam install .
  - run:
      name: Fsub
      command: make -k -C Fsub
  - run:
      name: Tutorial
      command: make -k -C Tutorial
  - run:
      name: Stlc
      command: make -k -C Stlc -B

jobs:
  coq.8.10:
    <<: *defaults
    docker:
    - image: ysli/lngen:8.10
  coq.8.11:
    <<: *defaults
    docker:
    - image: ysli/lngen:8.11
  coq.dev:
    <<: *defaults
    docker:
    - image: ysli/lngen

workflows:
  version: 2
  build:
    jobs:
    - coq.8.10
    - coq.8.11
    - coq.dev
